### ISSUE TITLE
Caching solution (REST API)

### ISSUE THREAD

**Issue by ItsEcholot** [hexcodech/booki#2]
What caching solution should be used to cache get requests and their answers?

[Example](https://github.com/kwhitley/apicache)

**Comment by Tyratox** [comment]
My first thought was no because many requests are unique and I didn't think we would be able to select specific queries to be "cacheable". But after I looked at the link I think it would be a very cool thing. (Especially because we're able to select which requests should and which should not be cached)

Sadly I'm not sure if the linked module ist (still) being updated as there are serious unsolved issues that already exist for some time.. (https://github.com/kwhitley/apicache/issues/3)
(Errors will also be cached and the only way to prevent this is doing the whole query before the function itself is executed)

**Comment by ItsEcholot** [comment]
Yeah the provided example is probably not really suitable for projects anymore as it seems outdated and unsupported.
I think we should give this subject a closer look in the future when we exactly know what the API has to handle.
